# Winlogbeat configuration for TinySocs
# Collects Windows + Sysmon logs and ships to Logstash on port 5044

winlogbeat.event_logs:
  - name: Application
  - name: System
  - name: Security
  - name: Microsoft-Windows-Sysmon/Operational
    ignore_older: 72h
    processors:
      - add_fields:
          target: ''
          fields:
            event.module: sysmon
            tags: [sysmon]

# Send to local Logstash container
output.logstash:
  hosts: ["localhost:5044"]