input {
  beats { port => 5044 }
}

filter {
  # optional filters go here
}

output {
  elasticsearch {
    hosts                   => ["https://opensearch:9200"]  # ← back to OS
    user                    => "admin"
    password                => "${OPENSEARCH_INITIAL_ADMIN_PASSWORD}"
    ssl                     => true
    ssl_verification_mode   => "none"    # demo certs
    index                   => "winlogbeat-%{+YYYY.MM.dd}"
  }
}

  # To also mirror to Elastic at the same time, add:
  # elasticsearch {
  #   hosts => ["http://elasticsearch:9200"]
  #   index => "winlogbeat-%{+YYYY.MM.dd}"
  # }
}
