from typing import Any, Protocol


class SIEMClient(Protocol):
    def search_kql(self, index: str, kql: str, size: int = 500) -> list[dict[str, Any]]: ...
    def aggregate_dsl(self, index: str, dsl: dict[str, Any]) -> dict[str, Any]: ...
