input { beats { port => 5044 } }
output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "winlogbeat-%{+YYYY.MM.dd}"
  }
  opensearch {
    hosts => ["https://opensearch:9200"]
    user  => "admin"
    password => "${OPENSEARCH_INITIAL_ADMIN_PASSWORD}"
    ssl_certificate_verification => false
    index => "winlogbeat-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}